name: yaml lint useing dagger
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dagger/dagger-for-github@v2
        with:
          cmds: |
            project update
            do lint
