name: yaml lint useing cue
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.17.0"
      - name: install cue
        run: go install cuelang.org/go/cmd/cue@latest
      - run: echo $PATH
      - run: ls -al /home/runner/go/bin
      - run: cue vet sample.yaml check.cue
