name: yaml lint useing cue
on: push
  
steps:
  - uses: actions/checkout@v3
  - uses: actions/setup-go@v3
  - name: install cue
    run: go install cuelang.org/go/cmd/cue@latest
  - run: cue vet sample.yaml check.cue 